apiVersion: v1

kind: Service


metadata:

  name: upi-api-service


spec:

  type: LoadBalancer


  selector:

    app: upi-api


  ports:


  - port: 80

    targetPort: 8080
